$(function(){
    initOwlCarousel();
  })

function initOwlCarousel(){
$('.owl-one').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:true,
    autoplayTimeout:2700,
    autoplayHoverPause:false,
    responsive:{
        0:{
            items:1
        },
        767:{
            items:2
        },
        991:{
            items:3
        }
    }
})

$('.owl-two').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    autoplay:true,
    autoplayTimeout:3000,
    autoplayHoverPause:false,
    responsive:{
        0:{
            items:1
        },
        476:{
            items:2
        },
        767:{
            items:4
        },
        991:{
            items:6
        }
    }
})
  }